name:                hylonn
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/hylonn#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base              >= 4.7   && < 5
  - lens              >= 4.15  && < 5
  - proto-lens        >= 0.2   && < 1
  - random
  - tensorflow
  - tensorflow-ops
  - tensorflow-core-ops
  - tensorflow-logging

executables:
  hylonn:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - hylonn

library:
  source-dirs: src    
  exposed-modules:

tests:
  spec:
    source-dirs:
      - test
      - src
    main: Test.hs
    dependencies:
      - tasty
      - tasty-discover
      - tasty-hspec

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - CPP 
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  #- DerivingStrategies
  - DuplicateRecordFields
  - EmptyCase
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImplicitParams
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoMonomorphismRestriction
  - OverloadedLabels
  - OverloadedLists
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  #- TypeFamilyDependencies
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  #- -Werror
  - -Wsemigroup
  - -fno-warn-orphans
  #- -Wwarn=unused-imports
  - -fprint-potential-instances
  - -fprint-typechecker-elaboration
